---
apiVersion: v1
kind: Pod
metadata:
  name: post-pod
  labels:
    author: adarsh
    type: db
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: pass
        - name: POSTGRES_USER
          value: myuse
        - name: POSTGRES_DB
          value: mydb
...
