---
apiVersion: v1
kind: Pod
metadata:
  name: jen-pod
  labels:
    author: adarsh
    type: ci-cd
spec:
  containers:
    - name: myjen
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090

