---
apiVersion: v1
kind: ReplicationController
metadata:
  name: apche-rc
  labels:
    author: adarsh
    type: reply
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        author: adarsh
        type: reply
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 7070
